### ISSUE TITLE
package not properly parsed

### ISSUE THREAD

**Issue by DaelDe** [Enteee/plantuml-parser#10]
The following diagram:
```
@startuml

interface _COMP_EXT1_IF1

package p1 as rmf{
  component _COMP8 
}

@enduml
```

results in 
```
SyntaxError: Expected "'", "(", "/'", "@enduml", "[", "\"", "abstract ", "class ", "cloud", "component ", "database", "digraph  ", "enum ", "folder", "frame", "interface ", "namespace", "node", "note ", "package", "rectangle", "skinparam ", "state", "tog  ether ", "usecase ", [ \t], or [A-Za-z0-9._] but "}" found.
```

I had a quick look to the grammar but did not find the root cause. I guess it should work however.

**Comment by DaelDe** [comment]
It works when the package name is quoted `as "rmf"` but plantuml also allows unquoted names here.

**Comment by Enteee** [comment]
thank you @DaelDe  for reporting this, the linked pull request should fix this issue. Can you please have a look at the [new fixture](https://github.com/Enteee/plantuml-parser/pull/13/files#diff-b73d541b8055bebeca4828f1f3247a81R1) and tell me if this is more or less what you would expect for this diagram.

**Comment by DaelDe** [comment]
Thank you, the new test is looking OK for me.
