### ISSUE TITLE
diagram ids

### ISSUE THREAD

**Issue by DaelDe** [Enteee/plantuml-parser#11]
**Is your feature request related to a problem? Please describe.**
Plantuml allows to assign an ID to a diagram for the purpose of reuse.

```
@startuml(id=MY_OWN_ID)
@enduml
```

See: http://plantuml.com/de/preprocessing

**Describe the solution you'd like**
Either the ID is parsed or everything after `@startuml` is ignored.

**Comment by DaelDe** [comment]
I would actually prefer that additional content after `@startuml` is ignored.

My use case is that diagrams are included in doxygen. In this context the command can have [parameters](http://www.doxygen.nl/manual/commands.html#cmdstartuml).

**Comment by Enteee** [comment]
good catch, there is very little documentation around this id feature.

Also the online plantuml parser just strips that Infomation. So I would assume this id should just contain all non white space ascii characters. What is still unclear to me is if id also supports quoting and what the expected bahaviour should be if there are whitespaces in the id

```
@startuml(id=what is the id now?)
Bob -> Alice : hello
@enduml
```

**Comment by Enteee** [comment]
just noticed that a missing closing parenthesis does not yield an error in plantuml
```
@startuml(id=missing
@enduml
```

this is something I don't what to support.

**Comment by Enteee** [comment]
I think using the `Name` terminal here is what we want.

```
Name
  = name:([A-Za-z0-9._]+)
  {
    return name.join('');
  }
```
