### ISSUE TITLE
Can't parse named diagrams

### ISSUE THREAD

**Issue by ali-habibzadeh** [Enteee/plantuml-parser#24]
**Describe the bug**
PUML diagrams can have names which comes right after the start directive.

Currently the tool breaks when passing such diagrams.

**To Reproduce**
1. try to parse or parseFile a named diagram
2. See error:
```
return new peg$SyntaxError(
           ^
SyntaxError: Expected "(", "\n", "\r\n", or [ \t] but "n" found.
```
**PlantUML**
```
@startuml name
  class A
  class B
  A --|> B
@enduml
```

**Expected behavior**
Tool should parse normally.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - node
 - v12

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by ali-habibzadeh** [comment]
Also doesn't support `!includeurl`. Shall I create a new issue for that?

**Comment by Enteee** [comment]
Thank you @ali-habibzadeh for this very useful bug report. I will try to reproduce this in a test and push a branch.

> Also doesn't support !includeurl. Shall I create a new issue for that?
yes please.

**Comment by Enteee** [comment]
This is to some degree related to #11. I am currently scanning the official documentation, but I can not see any reference to this. Also when I generate a diagram for:

```
@startuml name
A->B
@enduml
```

It redirects me to:
http://www.plantuml.com/plantuml/uml/SoWkIImgAStDKSXBp4tbSjIrS-9oICrB0Oe00000

which then contains the following diagram:
```
@startuml
A->B
@enduml
```
*Note*: `name` was removed.

Also I was scanning the official PlantUML documenation, and could not find a referece to `@startuml name`.

@ali-habibzadeh : are you sure this is a supported feature?

**Comment by Enteee** [comment]
Asked in the forum if this should be considered valid syntax: https://forum.plantuml.net/10366/are-diagram-names-a-supported-feature

**Comment by Enteee** [comment]
I never got a response. But since the official plantuml implementation just removes those names whilst completely ignoring them. I don't think this is a supported language feature.

**Comment by The-Lum** [comment]
Hello all,

Same answer as on https://github.com/qjebbs/vscode-plantuml/issues/393#issuecomment-887699255

> FYI: it is quickly defined here:
> - https://plantuml.com/sources
> 
> See also:
> - https://forum.plantuml.net/8202/how-to-define-output-filename
> - https://forum.plantuml.net/5483/please-specify-filename-@startuml-extension-automatically

And FYI, **all** those sources are valids:

```puml
@startuml BobAndAlice
Bob -> Alice : hello
@enduml

@startuml BAndA.png
B -> A : hello
@enduml

@startuml{myotherimage.png}
a->b
@enduml

@startuml{myotherimage.png,This is my other caption text,width=16cm}
b->a
@enduml
```
Ref. :
- https://forum.plantuml.net/5483/please-specify-filename-@startuml-extension-automatically
- https://forum.plantuml.net/1466

Regards.
